cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.urls import path
from . import views

app_name = 'myshop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail')
]

shop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('users/', include('users.urls')),
    path('', include('myshop.urls', namespace='shop')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register)

]

cart/models.py
from django.db import models

# Create your models here.

myshop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('Название категории', max_length=100, db_index=True)
    slug = models.SlugField('Имя ссылки на категорию', max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField('Название товара', max_length=150, db_index=True)
    slug = models.CharField('Название товара в адресе', max_length=150, db_index=True, unique=True)
    image = models.ImageField('Фотография', upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField('Описание товара', max_length=1000, blank=True)
    price = models.DecimalField('Цена товара', max_digits=10, decimal_places=0)
    available = models.BooleanField('Наличие', default=True)
    created = models.DateTimeField('Дата создания товара', auto_now_add=True)
    uploaded = models.DateTimeField('Дата обновления товара', auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])




class Data(models.Model):
    tele = models.CharField('Телефон', max_length=20)
    gmail = models.CharField('Почта', max_length=50)
    FIO = models.CharField('ФИО', max_length=100)
    Adres = models.TextField('Адрес')

    def __str__(self):
        return self.FIO


    class Meta:
        verbose_name = 'Данные о заказе'
        verbose_name_plural = 'Данные о заказах'

users/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

myshop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from myshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(reguest):
    if reguest.method != 'POST':
        form = UserCreationForm
    else: form = UserCreationForm(data=reguest.POST)

    if form.is_valid():
        new_user = form.save()
        login(reguest, new_user)
        return redirect('product:list')

    context = {'form': form}
    return render(reguest, 'users/register.html', context)

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
<h1 xmlns="http://www.w3.org/1999/html">Корзина покупок</h1>
<div style="background: #FFFFFF;
box-shadow: 0px 10px 40px rgba(0, 0, 0, 0.25); width: 80%; display:inline-block;">

      {% for item in cart %}
        {% with product=item.product %}
    <div style="width:90%;
    border-spacing:0;
    border-collapse: collapse;  display:inline-block;  margin: 10px 10px 10px 10px;">
              <a href="{{ product.get_absolute_url }}" style="float:left;">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="width:280px; height: 200px; padding: 20px 20px 20px 20px;">
              </a>
        <table>
        <thead>
        <th><h1 style="padding: 0 20px 20px 20px; vertical-align: center;">{{ product.name }}</h1></th>
        <th style="width: 500px; padding: 20px 0px 0px 0px;"><div><div style="float:left;position: static; vertical-align: center;"><form action="{% url 'cart:cart_add' product.id %}" method="post" style="float:left; position: relative;">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}<input type="submit" value="Обновить">
                  {% csrf_token %}
              </form></div></div></th>
        <th style="width: 100px; float: left; padding: 0px 0px 0px 0px; margin: 50px 0 0 0">{{ product.price }} ₽</th>
        <th style="width: 100px"><div style="border-radius: 20px; background: FF0000; width: 24px;
height: 24px;float:right;"><a href="{% url 'cart:cart_remove' product.id %}">Удалить товар</a></div></th>
        </thead>
        <tbody>
        <tr>

        </tr>
        </tbody>




  </table></div>

        {% endwith %}
      {% endfor %}
</div>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 22px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

/* Add a background color when the inputs get focus */
input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
}

button:hover {
    opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: #474e5d;
    padding-top: 50px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* Style the horizontal ruler */
hr {
    margin-bottom: 25px;
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 35px;
    top: 15px;
    font-size: 40px;
    font-weight: bold;
    color: #f1f1f1;
}

.close:hover,
.close:focus {
    color: #f44336;
    cursor: pointer;
}

/* Clear floats */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
       width: 100%;
    }
}
</style>
<div style="background: #FFFFFF; text-align: center; vertical-align: top;
box-shadow: 0px 10px 40px rgba(0, 0, 0, 0.25); width: 15%;height: 170px; border-collapse: collapse;  display:inline-block; ">
    <div><h3>Итого:   {{ cart.get_total_price }} ₽</h3></div>
    <div>{% with total_items=cart|length %}
<h3>Кол-во товаров: {{ total_items }} </h3>{% endwith %}</div>




<a href="/cart/forma">Оформить заказ</a>
</div>

{% endblock %}

myshop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}Мой магазин{% endblock %}</title>
<link rel="stylesheet">
</head>
<body>
<style>
    @import url(http://fonts.googleapis.com/css?family=Ubuntu);

body {
    margin:0;
    padding:0;
    font-family:helvetica, sans-serif;
}

h1, h2, h3, h4, h5 , h6 {
    font-family: 'Ubuntu', sans-serif; font-weight:normal;
}

a {
    text-decoration:none;
    color:#000;
}


a.button, input[type="submit"] {
    color:#000;
    background:#EEDFB8;
    border-radius:4px;
    padding:10px 20px;
    font-size:14px;
    border:0;
}

a.button.light {
    color:#000;
    background:#EEDFB8;
}


table.cart {
    margin-bottom:40px;
}

table.cart img {
    width:280px;
}



td input[type="submit"] {
    font-size:12px;
    padding:4px 10px;
}

form p label, form p input {
    float:left;
    clear:both;
}

form p label {
    font-size:14px;
    padding-bottom:4px;
}

form p input {
    width:300px;
    font-size:13px;
    margin-bottom:10px;
    padding:10px 12px;
    border:0;
    background:#EEDFB8;
    color:#000;
    border-radius:4px;
}

ul.errorlist {
   float:left;
   color:#ff0000;
   clear:both;
   font-size:13px;
   margin:0;
   padding:0;
}


#header {
    padding:10px 100px;
    font-size:18px;

}



#header .logo {
    font-family: 'Ubuntu', sans-serif;
    float:left;
    color:#333;
    font-size:22px;
    margin-right:10%;
}


#content {
    padding:0 100px;
    overflow:hidden;
}

#sidebar {
    width:220px;
    padding:30px 20px 0 0;
    float:left;
}

#sidebar ul{
    margin:0;
    padding:0;
}

#sidebar ul li {
    margin:0;
    list-style:none;
    padding:10px 14px;
}

#sidebar ul li a {
    display:block;
}

#sidebar ul li.selected {
    background:#EEDFB8;
    border-radius:4px;
}

#sidebar ul li.selected a {
    color:#000;
}

#main {
    float:left;
    width: 96%;
    margin-right:-220px;
    overflow:hidden;
}



.product-list .item img {
    width:100%;
    margin-bottom:8px;
}

.product-detail {
    text-align:justify;
}

.product-detail .price {
    color:#000;
    font-size:28px;
    font-weight:bold;
}

.product-detail img {
    width:40%;
    float:left;
    padding:0 20px 20px 0;
}

.product-detail h1 {
    margin-bottom:0;
}

.product-detail h2 {
    margin-top:10px;
}

.order-form {
    float:left;
}

.order-info {
    float:right;
    width:300px;
    background:#EEDFB8;
    padding:10px 20px;
    color:#000;
    border-bottom:4px solid #5993bb;
}

.order-info h3 {
    color:#5993bb;
}

.order-info ul li {
    margin:0;
    padding:0;
    font-size:14px;
}

.order-info p {
    font-weight:bold;
    float:right;
}

.order-info span {
    float:right;
}

.neg {
    color:#dc1616;
}

.languages {
   float:right;
   padding-top:4px;
   font-size:14px;
}

.languages ul {
    list-style:none;
    margin:0;
    padding:0;
    float:left;
}

.languages ul li {
    float:left;
    margin:0 0 0 10px;
    font-size:14px;
}

.languages p {
    float:left;
    margin:0;
}

.recommendations {
    clear:both;
}

.recommendations div {
    float:left;
}

.recommendations img {
    width:200px
}

.recommendations p {
    clear:both;
}

.recommendations.cart {
    width:60%;
    float:left;
    overflow:auto;
}

.recommendations.cart h3 {
    margin-top:0;
}

.recommendations.cart .item {
    margin-right:10px;
}

.recommendations.cart img {
    width:120px;
}

/* braintree hosted fields */
form div.field {
    font-size:13px;
    color:#666;
    width:300px;
    height:22px;
    margin-bottom:10px;
    padding:6px 12px;
    border:0;
    background:#efefef;
    color:#666;
    border-radius:4px;
}
footer{
position: static;

height: 366px;
left: 0px;
bottom: 0px;

background: #000000;
}
</style>
<header style=" padding:10px 100px;font-size:18px;">
<a href="/" class="logo"><img src="https://github.com/danila-1234/danila-1234.github.io/blob/master/%D0%9B%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF%20%D1%81%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%BC.png?raw=true">
</a>
<a href="#" style="position: absolute;
width: auto;
height: 35px;
left: 726px;
top: 46px;

filter: drop-shadow(0px 0px 0px rgba(0, 0, 0, 0.25));"></a>


    <a href="{% url 'cart:cart_detail' %}"><img src="https://danila-1234.github.io/Group%2024.png" style="position: absolute;
width: 148px;
height: 34px;
left: 1026px;
top: 36px;
filter: drop-shadow(0px 0px 0px rgba(0, 0, 0, 0.25));"></a>
</header>
<hr>
<div id="content">
{% block content %}{% endblock %}
</div>
<footer>
    <h2 style="position: absolute;
width: 521.17px;
height: 324.03px;
left: 763px;


font-family: 'Century Gothic';
font-style: normal;
font-weight: 400;
font-size: 18px;
line-height: 28px;

color: #FFFFFF;"><br>Адрес:<br>
141701, Московская область, г. Долгопрудный, пл. Собина, д. 1<br>
<br>Телефон:<br>
+7 (495) 369-45-93<br>
+7 (977) 758-71-25<br><br>Почта:<br>
mo_fiztechkoll@mosreg.ru</h2>
    <div style="position: absolute; left: 155px;"><br><br><h2 style="
font-family: 'Century Gothic';
font-style: normal;
font-weight: 400;
font-size: 18px;
line-height: 29px;

color: #FFFFFF;">Мы на карте:</h2><br>
<div style="position: relative;overflow:hidden;"><a href="https://yandex.ru/maps/org/gbpou_mo_fiztekh_kolledzh/1108017159/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">ГБПОУ МО Физтех-колледж</a><a href="https://yandex.ru/maps/214/dolgoprudniy/category/college/184106236/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:14px;">Колледж в Долгопрудном</a><a href="https://yandex.ru/maps/214/dolgoprudniy/category/further_education/184106162/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:28px;">Дополнительное образование в Долгопрудном</a><iframe src="https://yandex.ru/map-widget/v1/-/CCUZZOSKgC" width="360" height="200" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe></div>
</div>
</footer>
</body>
</html>

myshop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}

<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static 'img/no_image.png' %}{% endif %}" style="width: 300px; height: 300px;">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
</h2>
<p class="price">{{ product.price }} ₽</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="В корзину">
        {{ product.description|linebreaks }}
    </form>

</div>
{% endblock %}

myshop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">

<div class="dropdown">
  <button class="dropbtn"><h3>Категории</h3></button>
  <div class="dropdown-content">
    <ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Все</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
  </div>
</div>


</div>
<style>
    .dropbtn {
  color: black;
  background-color:#fff;
  font-size: 16px;
  border: none;
}

/* Контейнер <div> - необходим для размещения выпадающего содержимого */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Выпадающее содержимое (скрыто по умолчанию) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Ссылки внутри выпадающего списка */
.dropdown-content li {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

/* Показать выпадающее меню при наведении курсора */
.dropdown:hover .dropdown-content {display: block;}

.item{
width: 250px;
border: 2px solid black;
box-shadow: 0px 10px 40px rgba(0, 0, 0, 0.24);
padding: 20px 20px 20px 20px;
margin: 20px;
text-align: center;
line-height:1;
float:left;
}
</style>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}" style="padding: 20px 20px 20px 20px; width: 210px; height: 170px; text-align: center;">
</a>
    <h1>{{ product.price }} ₽ </h1><br>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
</div>
{% endfor %}
</div>
{% endblock %}